driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.6
  - name: centos-8.2
  - name: debian-10
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: ubuntu-20.04

suites:
  - name: default
    run_list:
      - recipe[motd::default]
